### ISSUE TITLE
[BUG] <Update-Station stops at 515/1294>

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd-src#260] opened 2023-02-18 00:11 UTC
### Version

ghostbsd-version -v 23.01.27

### Explain the issue and what happens

Will try "pkg clean" after writing this report.  Would like a suggestion on how to debug issue to see why  Python hangs at around 515/1294   515 seems to be a number this comes up.  I have 24GB freespace on the main "/"  root disk.   I have tried starting "Idle"  and set a breakpoint in a Python code line.   I  don't wish to add or have you debug.  Just a hint on a method to debug this using Python IDLE or other debug tool suite.

If this is a "user issue" problem,  I will gladly delete this issue.  Here to document my  testing issue of running close to edge of free space

### Explain how to reproduce the bug?

run  update-station from command line or click on the Icon in the upper right hand window, saying you have updates to install

Can you give me simple direction to debug this issue and find what runs out of space?

I did issue "sudo pkg clean"  deleted 1 GB of file 100%.  Still 4.9GB of file left in /var/cache/pkg directory

### What is the Expected behavior (if applicable)

Issue a warning or error message, saying ran out of room to continue farther in the update.   I have seen this issue before where it begins again from 1/1294 and work back to 515/1294  and hang again.  I did not kill the update-station task or restart.  It just restarts on its own.

### Additional context (if applicable)

![Installing_Update_515_Screenshot at 2023-02-17 23-57-30](https://user-images.githubusercontent.com/8184041/219818561-783d0742-0523-418a-8833-2e0f050ae919.png)
![Update_Station_Stuck_at_515_Screenshot at 2023-02-17 23-45-43](https://user-images.githubusercontent.com/8184041/219818562-93c1d857-dd26-4944-9261-b3d7b79622be.png)
[update-station_free_space.txt](https://github.com/ghostbsd/ghostbsd-src/files/10772506/update-station_free_space.txt)
[update-station_free_disk_space.txt](https://github.com/ghostbsd/ghostbsd-src/files/10772521/update-station_free_disk_space.txt)

**Comment by wb7odyfred** [comment] 2023-02-18 00:15
[update-station-vmstat.txt](https://github.com/ghostbsd/ghostbsd-src/files/10772538/update-station-vmstat.txt) 
Added vmstat information files.

**Comment by wb7odyfred** [comment] 2023-02-18 00:28
[update-station-ps-ax.txt](https://github.com/ghostbsd/ghostbsd-src/files/10772599/update-station-ps-ax.txt)
Maybe runs out of Process Space   ps  ax ?

**Comment by ericbsd** [comment] 2023-02-18 16:11
For pkg clean, you need to `sudo pkg clean -a` to delete all the pkg in the cache. `sudo pkg clean` delete only the old cache, not the new cached packages.

**Comment by ericbsd** [comment] 2023-02-18 16:12
How much ram you have and could you give me what `zfs list` give you?

**Comment by ericbsd** [comment] 2023-02-18 16:13
You can also run `sudo pkg upgrade -f` to see if you can see and error.

**Comment by ericbsd** [comment] 2023-02-18 16:16
I do not think you get out of space but I could be wrong.

**Comment by wb7odyfred** [comment] 2023-02-18 22:21
fred@fredTC93-pc:~/SSD_Install/Notes_New $ zfs list
NAME                                 USED  AVAIL     REFER  MOUNTPOINT
zroot                                199G  11.8G       96K  legacy
zroot/ROOT                          78.6G  11.8G       96K  legacy
zroot/ROOT/backup-2023-02-17-12-18     8K  11.8G     59.3G  /
zroot/ROOT/backup-2023-02-17-20-24     8K  11.8G     60.2G  /
zroot/ROOT/backup-2023-02-17-20-46     8K  11.8G     59.9G  /
zroot/ROOT/default                  78.6G  11.8G     60.2G  /
zroot/tmp                           5.66M  11.8G     5.66M  /tmp
zroot/usr                            121G  11.8G       96K  /usr
zroot/usr/home                       101G  11.8G      101G  /usr/home
zroot/usr/ports                     17.0G  11.8G     17.0G  /usr/ports
zroot/usr/src                       2.99G  11.8G     2.99G  /usr/src
zroot/var                           5.03M  11.8G       96K  /var
zroot/var/audit                       96K  11.8G       96K  /var/audit
zroot/var/crash                      104K  11.8G      104K  /var/crash
zroot/var/mail                      4.63M  11.8G     4.63M  /var/mail
zroot/var/tmp                        112K  11.8G      112K  /var/tmp

I have 8 gigabytes of DRAM memory and 4 gigabytes of SWAP partition space

**Comment by wb7odyfred** [comment] 2023-02-18 22:23
sudo pkg clean -a    is  a good idea
sudo pkg update -f
sudo pkg upgrade -fy

**Comment by wb7odyfred** [comment] 2023-02-18 22:30
> You can also run `sudo pkg upgrade -f` to see if you can see the error.

Yes,  I assume this will clear the present error and update my PC with February 2023 code pkgs.   I have had Update-Station stop before  at 514,515 out of 1200 pkgs, and wonder why this same number? 514

**Comment by ericbsd** [comment] 2023-03-16 20:36
So from DM on telegram, this was an issue from a missing dependency of some AWS packages.

I am trying to figure out how to improve the issue of the pkg upgrade hang.

**Comment by ericbsd** [comment] 2023-05-05 00:33
I can't reproduce it. It seems to have been related to a missing dependency in the repository.

I will close this and if this happens again open a new ticket.

**Closed by ericbsd** 2023-05-05 00:33 UTC
Labels: bug
