### ISSUE TITLE
[Bug]: GBSD does not identify Screen Resolution.

### ISSUE THREAD

**Issue by SunilSherkhane** [ghostbsd/ghostbsd-src#133] opened 2021-12-11 16:05 UTC
### Describe the bug

When trying to boot the GhostBSD by using USB it does not identify 1366x768 60Hz its not the problem with Monitor as the maximum frequency is set at 1366x768 60Hz. I tried re-configuring the Xorg and Check the Xrandr but failed. 

Link to my system pulled with ArchLinux

https://linux-hardware.org/?probe=b52176e414 

### How to reproduce the bug?

Boot the system by using USB which supports max screen resolution mentioned above.

### Expected behavior

Should load the desktop.

**Comment by ericbsd** [comment] 2021-12-15 13:36
Duplicate of #130

**Closed** 2021-12-15 13:36 UTC
Labels: bug, duplicate
