### ISSUE TITLE
[BUG] Cannot load nvidia-modeset for driver below 358.009

### ISSUE THREAD

**Issue by tim-pearce** [ghostbsd/ghostbsd-src#288] opened 2023-04-24 08:33 UTC
### Version

23.04.19

### Explain the issue and what happens

After applying the solution referenced in #280 it tries to load nvidia-modeset which fails and therefore does not solve the original problem.

### Explain how to reproduce the bug?

I went back to the problem backup environment and tried various ways of changing things. Even nvidia-settings was unable to display correctly.

### Additional context (if applicable)

On [https://forums.freebsd.org/threads/howto-setup-xorg-with-nvidias-driver.52311/](url) it says
nvidia-modeset is only available for driver versions >= 358.009
Therefore it will fail to load for the 304 and 340 drivers.
It is still the case that for my GeForce 405 xorg-server needs to stay at version 1.21.1.4 (or at least something less than 1.21.1.7).

**Comment by ericbsd** [comment] 2023-04-24 23:25
It is a bit more complicated than that. I just remembered that xconfig would try to install the old Nvidia driver in the build you installed, so there is no way that it will work on an updated system.

I have a bit more tweaking to do. Thank you for your patience.

**Note to me:**
I have to make a change to the installer to make sure it does not copy /xdriver and have xconfig does not rely on it once installed.

**Comment by ericbsd** [comment] 2023-05-20 16:29
To fix the issue without reinstalling, you must remove with `sudo rm -r /xdrivers` and do `sudo pkg upgrade -f`. The problem is that xconfig reinstall the old driver and it is not compatible with the latest system.

In newer ISO it will be fixed.

**Comment by tim-pearce** [comment] 2023-05-22 02:26
That seems to mostly fix may issues.
I am left with a curious issue, not sure if I need to raise a new issue yet.
When I switch to another console (eg Ctrl-Alt-F2) it works fine but when I do Ctrl-Alt-F9 and then return there is no keyboard response, however I can go to another one (eg Ctrl-Alt-F3) and that will work, until I do the Ctl-Alt-F9 switch again.

**Comment by ericbsd** [comment] 2023-05-22 18:39
That one is most likely xorg and Nvidia driver related.

**Closed** 2023-05-27 12:44 UTC
Labels: bug
