### ISSUE TITLE
[Bug]: Update_Station Fails to update in Fresh Install.  Software_Station shows 0 pkgs in Fresh Install

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd-src#179] opened 2022-03-10 23:56 UTC
### Describe the bug

Did a fresh Install to a SSD a couple days ago,  March 6, 2022 using the March 3, 2022 Latest version.
I think you are missing  'SUDO'   in front of "pkg update -f" command.   ( Check if bectl snapshot also fails?? )  I do not know how to confirm or deny "bectl snapshot operation"  )
[bectl snapshot](https://klarasystems.com/articles/managing-boot-environments/)
carl@fred-ghostbsd-pc ~ [1]> bectl list
BE      Active Mountpoint Space Created
default NR     /          7.19G 2022-03-06 23:22
So Update-Station has not run a "bectl snapshot" command

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
carl@fred-ghostbsd-pc ~> ps ax > save_ps_fresh.txt
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I    0:00.01 sudo update-station
3265  -  S    0:00.50 /usr/local/bin/python3.8 /usr/local/bin/update-station
3395  -  S    0:00.01 sudo update-station check-now
3396  -  S    0:00.23 /usr/local/bin/python3.8 /usr/local/bin/update-station ch
3404  -  S    0:00.00 /bin/sh -c yes | pkg update -f
3406  -  S    0:00.00 pkg update -f
3407  -  R    0:00.29 pkg update -f
3434  0  R+   0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> ps ax | grep bectl
3439  0  S+   0:00.00 grep --color=auto bectl
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I    0:00.01 sudo update-station
3265  -  S    0:00.50 /usr/local/bin/python3.8 /usr/local/bin/update-station
3395  -  S    0:00.01 sudo update-station check-now
3396  -  S    0:00.24 /usr/local/bin/python3.8 /usr/local/bin/update-station ch
3442  0  R+   0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I     0:00.01 sudo update-station
3265  -  S     0:00.50 /usr/local/bin/python3.8 /usr/local/bin/update-station
3395  -  I     0:00.01 sudo update-station check-now
3396  -  S     0:00.50 /usr/local/bin/python3.8 /usr/local/bin/update-station c
3574  0  S+    0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> pkg update -f
pkg: Insufficient privileges to update the repository catalogue.
carl@fred-ghostbsd-pc ~ [1]> pkg update -f

Line 56 of file [updateHandler.py file](https://github.com/ghostbsd/update-station/blob/master/src/updateHandler.py
)   what user is executing this code?  sudo user or just plain usr
```
def kerenel_verstion_change():
    pkg_update = Popen(
        'yes | pkg update -f',
        shell=True,
        stdout=PIPE,
        close_fds=True,
        universal_newlines=True,
        encoding='utf-8'
    )
```

### How to reproduce the bug?

Make new fresh install of GhostBSD latest version  March 2, 2022.
After logging in,  Menu --> Administration --> Software-Station   Notice that there are 0 (ZERO) packages available, not 31,000+  

Menu --> Administartion --> Update-Station    See that there are  19 new updates, and 1 reinstall  
![Update_problem__no_sudo_Screenshot at 2022-03-10 23-25-54](https://user-images.githubusercontent.com/8184041/157773724-2ed11a51-0719-44fa-b21f-48fe637d6cd7.png)
![Update_and_Station_running_Screenshot at 2022-03-10 23-01-52](https://user-images.githubusercontent.com/8184041/157773763-78941417-6e38-414b-b40e-0ef5bf8e8ce6.png)
![0_Packages_Software_Station_Screenshot at 2022-03-10 22-46-31](https://user-images.githubusercontent.com/8184041/157773778-22f84a08-fe17-4dc6-a636-1ae8aa3cefba.png)
![Sudo_missing_pkg_update_CLI_Screenshot at 2022-03-10 23-27-57](https://user-images.githubusercontent.com/8184041/157773828-e786a261-4ebb-4453-9f45-80e4959c5836.png)

### Expected behavior

I expect that "Update-Station"  would run "sudo pkg update -f " the first time, using the 'sudo' priviledge enhancement, since if  i run just "pkg update -f" it errors out with insufficient priviledges.

I saw the second time I ran  Software-Station  (after running the Update-Station to the menu display, then hitting close with out updating )  I saw that it was marked green in bottom status bar and was updating some files, before I got the camera to snap a picture.
![3rd_run_of_Screenshot at 2022-03-10 23-14-22](https://user-images.githubusercontent.com/8184041/157774231-711a5e7c-c685-4848-b97c-9684281bb676.png)
![2nd_time_running_Software_Station_Screenshot at 2022-03-10 22-55-48](https://user-images.githubusercontent.com/8184041/157774243-432007d8-171b-4274-83ea-aacab061c2d2.png)
![First_Update_Screenshot at 2022-03-10 22-51-00](https://user-images.githubusercontent.com/8184041/157774270-4dd96726-b8f4-47a6-91f1-d9bf692f1b96.png)

**Comment by ericbsd** [comment] 2022-03-11 00:14
Your bug report is confusing.

Update Station is already running as root no need of `sudo` for `pkg update -f`.

Also, I wouldn't recommend running Update Station and Software Station at the same time.

**Comment by wb7odyfred** [comment] 2022-03-11 00:43
sudo update-station is the LAST COMMAND ISSUED in the terminal window below.  It is hung up.  I will 'kill -9 update-station" process ids and run this command again.

```
carl@fred-ghostbsd-pc ~> software-station
carl@fred-ghostbsd-pc ~> update-station
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I      0:00.01 sudo update-station
3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
7973  -  S      0:00.01 sudo update-station check-now
7974  -  S      0:00.24 /usr/local/bin/python3.8 /usr/local/bin/update-station 
7982  -  S      0:00.00 /bin/sh -c yes | pkg update -f
7984  -  S      0:00.00 pkg update -f
7985  -  S      0:00.06 pkg update -f
7987  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I      0:00.01 sudo update-station
3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
7973  -  I      0:00.01 sudo update-station check-now
7974  -  S      0:00.42 /usr/local/bin/python3.8 /usr/local/bin/update-station 
8159  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I      0:00.01 sudo update-station
3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
8207  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I      0:00.01 sudo update-station
3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
8327  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> sudo update-station
/usr/local/bin/update-station:212: DeprecationWarning: Gtk.StatusIcon.set_tooltip_text is deprecated
  statusIcon.set_tooltip_text('Update Available')
/usr/local/bin/update-station:217: DeprecationWarning: Gtk.StatusIcon.set_visible is deprecated
  statusIcon.set_visible(False)
/usr/local/bin/update-station:218: DeprecationWarning: Gtk.StatusIcon.set_from_icon_name is deprecated
  statusIcon.set_from_icon_name('system-software-update')

(update-station:8420): Gdk-CRITICAL **: 16:37:54.714: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed


```

**Comment by wb7odyfred** [comment] 2022-03-11 00:49
`
carl@fred-ghostbsd-pc ~ [SIGINT]> 
carl@fred-ghostbsd-pc ~> ps ax | grep update
3252  -  I      0:00.01 sudo update-station
3265  -  S      0:00.62 /usr/local/bin/python3.8 /usr/local/bin/update-station
9130  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> kill -9 3252 3265
kill: 3265: Operation not permitted
carl@fred-ghostbsd-pc ~ [1]> ps ax | grep update
3265  -  S      0:00.62 /usr/local/bin/python3.8 /usr/local/bin/update-station
9193  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> ps ax | grep update
3265  -  S      0:00.62 /usr/local/bin/python3.8 /usr/local/bin/update-station
9196  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> sudo kill -9  3265
Password:
carl@fred-ghostbsd-pc ~> ps ax | grep update
9221  -  S      0:00.00 /bin/sh -c yes | pkg update -f
9223  -  S      0:00.00 pkg update -f
9224  -  S      0:00.05 pkg update -f
9228  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> ps ax | grep update
9255  0  S+     0:00.00 grep --color=auto update
carl@fred-ghostbsd-pc ~> 
`

**Comment by ericbsd** [comment] 2022-03-11 00:51
> sudo update-station is the LAST COMMAND ISSUED in the terminal window below. It is hung up. I will 'kill -9 update-station" process ids and run this command again.
> 
> ```
> carl@fred-ghostbsd-pc ~> software-station
> carl@fred-ghostbsd-pc ~> update-station
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 3252  -  I      0:00.01 sudo update-station
> 3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
> 7973  -  S      0:00.01 sudo update-station check-now
> 7974  -  S      0:00.24 /usr/local/bin/python3.8 /usr/local/bin/update-station 
> 7982  -  S      0:00.00 /bin/sh -c yes | pkg update -f
> 7984  -  S      0:00.00 pkg update -f
> 7985  -  S      0:00.06 pkg update -f
> 7987  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 3252  -  I      0:00.01 sudo update-station
> 3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
> 7973  -  I      0:00.01 sudo update-station check-now
> 7974  -  S      0:00.42 /usr/local/bin/python3.8 /usr/local/bin/update-station 
> 8159  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 3252  -  I      0:00.01 sudo update-station
> 3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
> 8207  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 3252  -  I      0:00.01 sudo update-station
> 3265  -  S      0:00.60 /usr/local/bin/python3.8 /usr/local/bin/update-station
> 8327  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> sudo update-station
> /usr/local/bin/update-station:212: DeprecationWarning: Gtk.StatusIcon.set_tooltip_text is deprecated
>   statusIcon.set_tooltip_text('Update Available')
> /usr/local/bin/update-station:217: DeprecationWarning: Gtk.StatusIcon.set_visible is deprecated
>   statusIcon.set_visible(False)
> /usr/local/bin/update-station:218: DeprecationWarning: Gtk.StatusIcon.set_from_icon_name is deprecated
>   statusIcon.set_from_icon_name('system-software-update')
> 
> (update-station:8420): Gdk-CRITICAL **: 16:37:54.714: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
> 
> ^CTraceback (most recent call last):
>   File "/usr/local/bin/update-station", line 734, in <module>
>     Gtk.main()
>   File "/usr/local/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1649, in main
>     return _Gtk_main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
>     next(self.gen)
>   File "/usr/local/lib/python3.8/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
>     signal.default_int_handler(signal.SIGINT, None)
> KeyboardInterrupt
> carl@fred-ghostbsd-pc ~ [SIGINT]> 
> ```

The only error is seen in that is generated by a ctrl+C

**Comment by ericbsd** [comment] 2022-03-11 00:52
> ```
> carl@fred-ghostbsd-pc ~ [SIGINT]> 
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 3252  -  I      0:00.01 sudo update-station
> 3265  -  S      0:00.62 /usr/local/bin/python3.8 /usr/local/bin/update-station
> 9130  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> kill -9 3252 3265
> kill: 3265: Operation not permitted
> carl@fred-ghostbsd-pc ~ [1]> ps ax | grep update
> 3265  -  S      0:00.62 /usr/local/bin/python3.8 /usr/local/bin/update-station
> 9193  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 3265  -  S      0:00.62 /usr/local/bin/python3.8 /usr/local/bin/update-station
> 9196  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> sudo kill -9  3265
> Password:
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 9221  -  S      0:00.00 /bin/sh -c yes | pkg update -f
> 9223  -  S      0:00.00 pkg update -f
> 9224  -  S      0:00.05 pkg update -f
> 9228  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> ps ax | grep update
> 9255  0  S+     0:00.00 grep --color=auto update
> carl@fred-ghostbsd-pc ~> 
> ```

stop sending `ps ax` command it does not help.

**Comment by ericbsd** [comment] 2022-03-11 00:53
If you can clearly explain to me the problem I will close the ticket.

**Comment by wb7odyfred** [comment] 2022-03-11 00:55
`sudo update-station check-now
default            192.168.0.1        UGS       wlan0
carl@fred-ghostbsd-pc ~> 
`
update-station check-now, says there are updates

The problem is running update-station  just exits.   It says that there are 19 updates and 1 reinstall.  Nothing Happens.   What is update-station suppose to accomplish.

**Comment by ericbsd** [comment] 2022-03-11 01:00
Did you press install?

**Comment by ericbsd** [comment] 2022-03-11 01:21
What is the error in the terminal when pressing Install Updates?

**Comment by ericbsd** [comment] 2022-03-11 01:30
I am closing this issue, there is no clear explanation error output, and I cannot reproduce the behavior described in the chat.

Without the error output, there is nothing I can do.

**Closed by ericbsd** 2022-03-11 01:30 UTC
Labels: bug

**Comment by wb7odyfred** [comment] 2022-03-11 01:57
There is NO ERROR, it just exits the program.

```
```
sudo update-station
/usr/local/bin/update-station:212: DeprecationWarning: Gtk.StatusIcon.set_tooltip_text is deprecated
  statusIcon.set_tooltip_text('Update Available')
/usr/local/bin/update-station:217: DeprecationWarning: Gtk.StatusIcon.set_visible is deprecated
  statusIcon.set_visible(False)
/usr/local/bin/update-station:218: DeprecationWarning: Gtk.StatusIcon.set_from_icon_name is deprecated
  statusIcon.set_from_icon_name('system-software-update')

(update-station:13553): Gdk-CRITICAL **: 17:49:26.937: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by ericbsd** [comment] 2022-03-11 03:26
Update Station command without check-now option runs like daemon. So nothing will start right away with sudo update-station.

If you want to run update right away you need to run sudo update-station check-now.

So when the window appears press install updates if there is a problem it will be showing in the terminal.

**Comment by ericbsd** [comment] 2022-04-02 19:18
I think I found a problem related to this, when I start it with check-now it exit without error.
