### ISSUE TITLE
[BUG] Update of xorg-server to 21.1.7 causes NVIDIA GeForce 405 failure

### ISSUE THREAD

**Issue by tim-pearce** [ghostbsd/ghostbsd-src#280] opened 2023-04-04 01:10 UTC
### Version

23.03.17 (XFCE)

### Explain the issue and what happens

After update today I was able to login but there was no desktop background and nothing on the desktop or even a context menu.
When I opened a terminal window there was no keyboard access. On reboot there was no change.
The terminal window was placed over the panel.
NOTE: I was able to enter my password to login but it seems the keyboard was ignored after that.
Tried to check dmesg but that's when I realised the keyboard wasn't working. Maybe I should have tried that before logging into the GUI!

### Explain how to reproduce the bug?

Do the update and reboot.

### What is the Expected behavior (if applicable)

Desktop and keyboard should still work.

### Additional context (if applicable)

I have now reverted to the backup environment prior to the update.

**Comment by tim-pearce** [comment] 2023-04-04 01:26
Rebooted into the 'fail' environment.
Ctrl-Alt-F2 and login as root
dmesg and nothing seemed out of the ordinary
Ctl-Alt-F9 and login to GUI
Ctl-Alt-F2 and no keyboard, not even enter
However Ctl-Alt-F9 and Ctl-Alt-F2 work!
Reboot using mouse and return here in the working environment.

**Comment by tim-pearce** [comment] 2023-04-06 09:08
I mounted the failed backup environment and found st the end of /var/log/daemon.log
Apr  4 09:19:59 bob console-kit-daemon[1710]: GLib-CRITICAL: g_close(fd:-1) failed with EBADF. This is not a valid file descriptor
Apr  4 09:19:59 bob console-kit-daemon[1710]: WARNING: Error waiting for native console 9 activation: Inappropriate ioctl for device

This would be where I did Ctl-Alt-F2 and then tried to get back to the GUI with Ctl-Alt-F9. 
By this point I had no 'normal' keyboard response.

In /var/log/lightdm/x-0.log I have 
X.Org X Server 1.21.1.7 (vs X.Org X Server 1.21.1.4 previously - everything else seems unchanged)
X Protocol Version 11, Revision 0
Current Operating System: FreeBSD bob 13.1-STABLE FreeBSD 13.1-STABLE GENERIC amd64
 
Current version of pixman: 0.42.2
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Tue Apr  4 09:14:28 2023
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/local/share/X11/xorg.conf.d"
================ WARNING WARNING WARNING WARNING ================
This server has a video driver ABI version of 25.2 that this
driver does not officially support.  Please check
http://www.nvidia.com/ for driver updates or downgrade to an X
server with a supported driver ABI.
=================================================================
(WW) NVIDIA: The driver will continue to load, but may behave strangely.
(WW) NVIDIA: This driver was compiled against the X.Org server SDK from commit e6ef2b12404dfec7f23592a3524d2a63d9d25802 and may not be compatible with the final version of this SDK.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86BrightnessAuto
> Warning:          Could not resolve keysym XF86DisplayOff
and many similar

**Comment by tim-pearce** [comment] 2023-04-06 10:14
I put a pkg lock on xorg-server and redid the update. Everything appears to be working now. Will report back if it stops working.

**Comment by ericbsd** [comment] 2023-04-06 20:27
What is your graphics card?

**Comment by tim-pearce** [comment] 2023-04-06 21:50
GPU: GT218 [GeForce 405] and my video driver is nvidia-driver-340-340.108_3
After I went to bed last night (I'm in Western Australia UTC+8) it occurred to me that it could be related to the card. When I get a chance I will try the update on one of my other PCs that are running the same environment with different video hardware.
I have two of these cards, which cost me nothing and up to now have worked just fine with GhostBSD.

**Comment by tim-pearce** [comment] 2023-04-06 22:24
Update worked on this PC with GPU: 82Q35 Express Integrated Graphics Controller

**Comment by tim-pearce** [comment] 2023-04-06 23:11
And on this laptop with GPU: 4th Gen Core Processor Integrated Graphics Controller
According to [https://wiki.freebsd.org/Graphics#NVIDIA_graphics](url)
nvidia-driver-304 does not support xorg-server 1.20 or greater
so looks like I've been lucky that it has worked so far.
I guess my solution is to keep it locked at 21.1.4 or get another graphics card!

**Comment by ericbsd** [comment] 2023-04-10 23:36
Duplicate of #231.

**Comment by ericbsd** [comment] 2023-04-10 23:55
The problem is here https://github.com/ghostbsd/ghostbsd-src/issues/231#issuecomment-1435735612, and I have a workaround for it.

**Comment by ericbsd** [comment] 2023-04-10 23:58
@tim-pearce, in the meantime, you can add those lines below in /etc/X11/xorg.conf.
```
Section "ServerFlags"
	Option "IgnoreABI" "1"
EndSection
```

**Comment by tim-pearce** [comment] 2023-04-11 00:12
I currently have 
Section "Server Flags"
 Option "ignoreABI" "true"
EndSection
Will try with the slightly different syntax now.

**Comment by tim-pearce** [comment] 2023-04-11 00:19
I still get the message in the log. Will try the upgrade again.

**Comment by tim-pearce** [comment] 2023-04-11 00:31
It doesn't work. After the update I still get the same issue. Have dropped back to the BE.

**Comment by tim-pearce** [comment] 2023-04-11 01:06
I think it's come to the point where IgnoreABI no longer works.
I gather this flag is telling to run even though there is a non-matching interface.
Up till now I've gotten away with it however this PC occasionally does a spontaneous reboot (been a few weeks but sometimes it'll happen several times in one day). Can't be certain but I think it coincides with increased graphics 'activity'.
My guess is that the mismatch with the interface has now reached a point where an invalid call is being made consistently.

**Comment by ericbsd** [comment] 2023-04-15 15:30
I am testing a new configuration on my iMac with the same issue.

**Comment by ericbsd** [comment] 2023-04-15 19:18
Ok, I fixed the issue on my iMac. A new iso will be ready soon.

**Comment by ericbsd** [comment] 2023-04-17 21:55
The ISO with the fix https://www.ghostbsd.org/download#latest_builds

**Closed by ericbsd** 2023-04-17 21:55 UTC
Labels: bug, duplicate

**Comment by ericbsd** [comment] 2023-04-18 23:31
If you do not want to reinstall, update all the packages and run `sudo xconfig auto`  in the shell.

**Comment by ericbsd** [comment] 2023-04-18 23:32
Also, I think my iMac is the same here as yours.

**Comment by tim-pearce** [comment] 2023-04-19 03:22
That didn't seem to work for me although I think I ran the xconfig before the update - which only updated xorg-server.
Did see a message flash past on startup about modeset - couldn't find such message in any logs - maybe I don't know where to look.
Did see a message in a log saying it couldn't find glxservernvidia.

**Comment by tim-pearce** [comment] 2023-04-19 03:34
Screenfetch on my iMac says:
OS: Manjaro 22.0.0 Sikaris
Kernel: x86_64 Linux 5.15.81-1-MANJARO
Resolution: 1920x1080
Disk: 394G / 474G (87%)
CPU: Intel Core2 Duo E7600 @ 2x 3.059GHz
GPU: AMD/ATI RV730/M96-XT [Mobility Radeon HD 4670]
RAM: 911MiB / 3898MiB

**Comment by tim-pearce** [comment] 2023-04-24 07:45
I am using the nvidia-driver-340 but when I do kldload nvidia-modeset it tells me it does not exist!
